name: Deploy Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Instalar dependências
        run: bun install

      - name: Gerar documentação TypeDoc (Gera dentro de /docs)
        run: bun run docs 

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Construir site padrão do Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Fazer upload dos artefatos (Site Finalizado)
        uses: actions/upload-pages-artifact@v3
        with:
          # Agora fazemos upload da pasta _site gerada pelo Jekyll, não da docs crua
          path: './_site'

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4